apiVersion: v1
kind: ConfigMap
metadata:
  name: wevoteserver-config
  namespace: wevote
data:
  # Primary Database Connection
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "wevote"
  DATABASE_USER: "wevote"
  DATABASE_PASSWORD: "MyDBpassword"
  

  # Read-only database connection
  DATABASE_HOST_READONLY: "postgres"
  DATABASE_PORT_READONLY: "5432"
  DATABASE_NAME_READONLY: "wevote"
  DATABASE_USER_READONLY: "wevote"
  DATABASE_PASSWORD_READONLY: "MyDBpassword"
  
  # Django configuration
  DJANGO_SUPERUSER_EMAIL: "email@test.com"
  DJANGO_SUPERUSER_PASSWORD: "MyAdminPassword"
  SECRET_KEY: "change-this-to-a-random-secret-ey-in-production"
  DJANGO_DEBUG: "False"
  ALLOWED_HOSTS: "*"
  
  # WeVote specific (if needed)
  SERVER_IS_SOURCE_OF_TRUTH: "True"
